# Generated by Django 2.2.5 on 2019-11-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogtag',
            name='owner_phone',
            field=models.TextField(default=12345678),
            preserve_default=False,
        ),
    ]
